# Generated by Django 6.1.1 on 2026-09-02 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_explorecollection_exploreimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploreimage',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='exploreimage',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='score.explorecollection'),
        ),
    ]
