# Generated by Django 6.1.1 on 2026-09-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_exploreimage_file_hash_alter_exploreimage_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploreimage',
            name='file_size_kb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
